<?xml version="1.0"?>
<!--
  AutoRacer URDF 模型
  Ackermann 转向 RC 小车，参考 wheeltec top_akm_bs_robot.urdf

  坐标系约定 (ROS REP-103):
    X = 前, Y = 左, Z = 上
    base_link = 后轴中心，轴高度 (Z=0.11m above ground)

  实测参数 (2026-01-29):
    车辆: 长0.85m, 宽0.50m, 高0.40m
    轴距: 0.54m (前轴距车头0.15m, 后轴距车尾0.16m)
    轮距: 0.48m
    轮径: 0.11m (半径)
    最大转向角: 0.393 rad (≈22.5°)
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="autoracer">

  <!-- ==================== 参数定义 ==================== -->
  <!-- 底盘尺寸 -->
  <xacro:property name="chassis_length" value="0.85"/>
  <xacro:property name="chassis_width" value="0.50"/>
  <xacro:property name="chassis_height" value="0.20"/>

  <!-- Ackermann 运动学参数 -->
  <xacro:property name="wheelbase" value="0.54"/>
  <xacro:property name="track_width" value="0.48"/>
  <xacro:property name="wheel_radius" value="0.11"/>
  <xacro:property name="wheel_width" value="0.08"/>
  <xacro:property name="max_steering_angle" value="0.393"/>

  <!-- 底盘布局 (base_link 在后轴中心) -->
  <xacro:property name="front_axle_to_front" value="0.15"/>
  <xacro:property name="rear_axle_to_rear" value="0.16"/>

  <!-- base_link 高度 (轴心离地高度) -->
  <xacro:property name="axle_height" value="${wheel_radius}"/>

  <!-- 底盘中心相对 base_link 的 X 偏移 -->
  <!-- base_link 在后轴，底盘几何中心在 X = (wheelbase - rear_axle_to_rear + front_axle_to_front) / 2 -->
  <xacro:property name="chassis_x_offset" value="${(wheelbase - rear_axle_to_rear + front_axle_to_front) / 2.0}"/>

  <!-- 底盘底面相对 base_link 的 Z 偏移 (底盘底面在轴心上方一小段) -->
  <xacro:property name="chassis_z_offset" value="0.02"/>

  <!-- 车辆质量 (估计值) -->
  <xacro:property name="chassis_mass" value="8.0"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="steering_mass" value="0.1"/>

  <!-- 传感器位置 (相对 base_link) -->
  <xacro:property name="lidar_x" value="0.24"/>
  <xacro:property name="lidar_z" value="0.39"/>
  <xacro:property name="lidar_yaw" value="-1.5708"/>

  <xacro:property name="zed_x" value="0.34"/>
  <xacro:property name="zed_z" value="0.29"/>

  <!-- ==================== 材质定义 ==================== -->
  <material name="chassis_color">
    <color rgba="0.2 0.2 0.2 1"/>
  </material>
  <material name="wheel_color">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>
  <material name="steering_color">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  <material name="sensor_color">
    <color rgba="0.3 0.3 0.8 1"/>
  </material>

  <!-- ==================== 惯性矩阵宏 ==================== -->
  <!-- 长方体惯性 -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m*(y*y+z*z)/12.0}" ixy="0" ixz="0"
             iyy="${m*(x*x+z*z)/12.0}" iyz="0"
             izz="${m*(x*x+y*y)/12.0}"/>
  </xacro:macro>

  <!-- 圆柱体惯性 (绕 Y 轴旋转的轮子) -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12.0}" ixy="0" ixz="0"
             iyy="${m*r*r/2.0}" iyz="0"
             izz="${m*(3*r*r+h*h)/12.0}"/>
  </xacro:macro>

  <!-- ==================== 车轮宏 ==================== -->
  <xacro:macro name="wheel_link" params="name">
    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="wheel_color"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- ==================== base_link (后轴中心，轴高度) ==================== -->
  <link name="base_link">
    <inertial>
      <origin xyz="${chassis_x_offset} 0 ${chassis_z_offset + chassis_height/2.0}" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
    </inertial>
    <visual>
      <origin xyz="${chassis_x_offset} 0 ${chassis_z_offset + chassis_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="chassis_color"/>
    </visual>
    <collision>
      <origin xyz="${chassis_x_offset} 0 ${chassis_z_offset + chassis_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- ==================== 后轮 (continuous joints) ==================== -->
  <!-- 左后轮 -->
  <xacro:wheel_link name="rear_left_wheel_link"/>
  <joint name="rear_left_wheel_joint" type="continuous">
    <origin xyz="0 ${track_width/2.0} 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="rear_left_wheel_link"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- 右后轮 -->
  <xacro:wheel_link name="rear_right_wheel_link"/>
  <joint name="rear_right_wheel_joint" type="continuous">
    <origin xyz="0 ${-track_width/2.0} 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="rear_right_wheel_link"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ==================== 前轮转向 (revolute + continuous) ==================== -->
  <!-- 左前转向节 -->
  <link name="front_left_steering_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${steering_mass}"/>
      <xacro:box_inertia m="${steering_mass}" x="0.05" y="0.05" z="0.05"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.02" length="0.05"/>
      </geometry>
      <material name="steering_color"/>
    </visual>
  </link>
  <joint name="front_left_steering_joint" type="revolute">
    <origin xyz="${wheelbase} ${track_width/2.0} 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="front_left_steering_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-max_steering_angle}" upper="${max_steering_angle}" effort="10" velocity="1.0"/>
  </joint>

  <!-- 左前轮 -->
  <xacro:wheel_link name="front_left_wheel_link"/>
  <joint name="front_left_wheel_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="front_left_steering_link"/>
    <child link="front_left_wheel_link"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- 右前转向节 -->
  <link name="front_right_steering_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${steering_mass}"/>
      <xacro:box_inertia m="${steering_mass}" x="0.05" y="0.05" z="0.05"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.02" length="0.05"/>
      </geometry>
      <material name="steering_color"/>
    </visual>
  </link>
  <joint name="front_right_steering_joint" type="revolute">
    <origin xyz="${wheelbase} ${-track_width/2.0} 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="front_right_steering_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-max_steering_angle}" upper="${max_steering_angle}" effort="10" velocity="1.0"/>
  </joint>

  <!-- 右前轮 -->
  <xacro:wheel_link name="front_right_wheel_link"/>
  <joint name="front_right_wheel_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="front_right_steering_link"/>
    <child link="front_right_wheel_link"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ==================== 传感器 link ==================== -->
  <!-- LiDAR C32 (固定在 base_link 上) -->
  <link name="laser">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <xacro:cylinder_inertia m="0.5" r="0.05" h="0.07"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.07"/>
      </geometry>
      <material name="sensor_color"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.07"/>
      </geometry>
    </collision>
  </link>
  <joint name="laser_joint" type="fixed">
    <origin xyz="${lidar_x} 0 ${lidar_z}" rpy="0 0 ${lidar_yaw}"/>
    <parent link="base_link"/>
    <child link="laser"/>
  </joint>

  <!-- ZED X 深度相机 (固定在 base_link 上) -->
  <link name="zed_camera_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <xacro:box_inertia m="0.2" x="0.04" y="0.17" z="0.03"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.17 0.03"/>
      </geometry>
      <material name="sensor_color"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.17 0.03"/>
      </geometry>
    </collision>
  </link>
  <joint name="zed_camera_joint" type="fixed">
    <origin xyz="${zed_x} 0 ${zed_z}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="zed_camera_link"/>
  </joint>

</robot>
